# Miner Strategy Configuration

# Email Settings
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender_name: Miner Strategy Scanner

# Trading Parameters
trading:
  max_risk_per_trade: 0.03  # 3% of account
  max_total_risk: 0.06      # 6% total portfolio risk
  default_account_size: 1000000  # ₹10 Lakhs

# Indicator Settings
indicators:
  stochastic:
    period: 14
    smooth_k: 3
    smooth_d: 3
    overbought: 80
    oversold: 20
  
  rsi:
    period: 14
    overbought: 70
    oversold: 30
    neutral: 50
  
  macd:
    fast: 12
    slow: 26
    signal: 9

# Timeframes
timeframes:
  larger: "1d"        # Daily for trend
  smaller: "60m"      # 60-minute for entries
  
# Fibonacci Ratios
fibonacci:
  internal_retracements: [0.236, 0.382, 0.500, 0.618, 0.786]
  external_retracements: [1.272, 1.618, 2.618]
  projections: [0.618, 1.000, 1.618]

# Backtesting
backtest:
  start_date: "2015-01-01"
  end_date: "2025-10-24"
  initial_capital: 1000000
  commission: 0.001  # 0.1% per trade
  slippage: 0.001    # 0.1% slippage

# Reporting
reporting:
  max_setups_per_direction: 10
  include_watchlist: true
  watchlist_threshold: 0.8  # 80% of criteria met
